/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./models/simple_low_poly_helicopter.glb 
Author: Taha Bin Ashar (https://sketchfab.com/tahabinasharchaudhary)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-low-poly-helicopter-d7a4f68877ac41c28e793013cb17287b
Title: Simple low poly helicopter
*/

import { useEffect, useMemo, useRef } from "react";

import { a, useSpring } from "@react-spring/three";
import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

import { useProjectedLocation } from "../../store/store.js";
import { transformCoordinates } from "../../utils/coordinateTransforms.js";

export function Helicopter({ coordinateScales, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/simple_low_poly_helicopter.glb",
  );
  const { actions } = useAnimations(animations, group);

  // Change material color to pink
  if (materials.Material) {
    materials.Material.color.set(0xfca3b7);
  }

  const projectedLocation = useProjectedLocation();

  const transformedLocation = useMemo(() => {
    if (!projectedLocation) return null;
    if (!coordinateScales) return null;
    if (projectedLocation.index === 0) return null;

    return transformCoordinates(
      [projectedLocation.coords],
      coordinateScales,
      projectedLocation.index,
    )[0];
  }, [projectedLocation, coordinateScales]);
  const [springs, api] = useSpring(() => ({
    position: [0, 0, 0],

    config: { tension: 170, friction: 26 }, // tweak as you like
  }));

  useEffect(() => {
    if (!transformedLocation) return;

    const x = transformedLocation[0];
    const y = transformedLocation[1];
    const z = transformedLocation[2];

    // Ensure all values are valid numbers before animating
    if (!Number.isFinite(x) || !Number.isFinite(y) || !Number.isFinite(z)) {
      return;
    }

    api.start({
      position: [x, y + 0.2, z],
    });
  }, [transformedLocation, api]);

  useEffect(() => {
    if (!transformedLocation) return;
    if (actions && Object.keys(actions).length > 0) {
      const firstAction = Object.values(actions)[0];
      firstAction.setEffectiveTimeScale(1.5).play();
    }
  }, [actions, transformedLocation]);

  useFrame(({ clock }) => {
    if (!group.current) return;

    const t = clock.getElapsedTime();
    group.current.rotation.y +=
      (0.01 + Math.sin(t * 0.7) * 0.008) * Math.cos(t * 0.3);
    group.current.rotation.z = Math.cos(t * 0.4) * 0.2;
  });

  if (!transformedLocation) return null;

  return (
    <a.group
      ref={group}
      {...props}
      dispose={null}
      position={springs.position}
      rotation={[0, Math.PI, 0]}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube_0" position={[0, 3.864, 0]}>
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials.Material}
                />
              </group>
              <group name="Cube001_1" position={[0.006, 4.892, -0.514]}>
                <mesh
                  name="Object_6"
                  geometry={nodes.Object_6.geometry}
                  material={materials.Material}
                />
              </group>
              <group name="Cube002_2" position={[0.531, 5.48, -8.971]}>
                <mesh
                  name="Object_8"
                  geometry={nodes.Object_8.geometry}
                  material={materials.Material}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </a.group>
  );
}

useGLTF.preload("/simple_low_poly_helicopter.glb");
