/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./models/ufo/scene.gltf --transform 
Files: ./models/ufo/scene.gltf [23.89KB] > /Users/toto/Documents/Git/gltfjsx/scene-transformed.glb [41.13KB] (-72%)
Author: Graphfun (https://sketchfab.com/the_3d_animate_guy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ufo-f7ac46de718a444384a73e953d49997c
Title: UFO
*/

import React from "react";

import { useAnimations, useGLTF } from "@react-three/drei";
import { useGraph } from "@react-three/fiber";
import { SkeletonUtils } from "three-stdlib";
export function Model(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/scene-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  React.useEffect(() => {
    const action = actions[Object.keys(actions)[0]];
    if (action) action.play();
  }, [actions]);

  React.useEffect(() => {
    Object.values(materials).forEach((mat) => {
      mat.metalness = 0;
      mat.roughness = 0.9;
    });
  }, [materials]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_7.skeleton}
          scale={1.21}
        />
        <skinnedMesh
          name="Object_8"
          geometry={nodes.Object_8.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_8.skeleton}
          scale={1.21}
        />
        <skinnedMesh
          name="Object_9"
          geometry={nodes.Object_9.geometry}
          material={materials.PaletteMaterial002}
          skeleton={nodes.Object_9.skeleton}
          scale={1.21}
        />
        <skinnedMesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={materials.PaletteMaterial003}
          skeleton={nodes.Object_10.skeleton}
          scale={1.21}
        />
        <skinnedMesh
          name="Object_11"
          geometry={nodes.Object_11.geometry}
          material={materials.PaletteMaterial004}
          skeleton={nodes.Object_11.skeleton}
          scale={1.21}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
