/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [23.89KB] > C:\Users\t.gilbert\Downloads\ufo\scene-transformed.glb [41.12KB] (-72%)
Author: Graphfun (https://sketchfab.com/the_3d_animate_guy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ufo-f7ac46de718a444384a73e953d49997c
Title: UFO
*/

import { useEffect, useMemo, useRef } from "react";

import { a, useSpring } from "@react-spring/three";
import { useAnimations, useGLTF } from "@react-three/drei";
import { useGraph } from "@react-three/fiber";
import { useTheme } from "styled-components";
import { SkeletonUtils } from "three-stdlib";

import { useProjectedLocation } from "../../store/store.js";
import { transformCoordinates } from "../../utils/coordinateTransforms.js";

export function Model({ coordinateScales, ...props }) {
  const group = useRef();
  const { scene, animations } = useGLTF("/scene-transformed.glb");
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  const theme = useTheme();
  const palette = theme.colors[theme.currentVariant];

  useEffect(() => {
    const action = actions[Object.keys(actions)[0]];
    if (action) action.play();
  }, [actions]);

  useEffect(() => {
    Object.values(materials).forEach((mat) => {
      mat.metalness = 0.5;
      mat.roughness = 0.9;
    });
    if (materials.PaletteMaterial001) {
      materials.PaletteMaterial001.color.set(palette["--color-secondary"]);
    }
    const mat002 = materials.PaletteMaterial002;
    if (mat002) {
      mat002.color.set(palette["--color-text"]);
      mat002.emissive.set(palette["--color-text"]);
      // eslint-disable-next-line react-hooks/immutability
      mat002.emissiveIntensity = 1;
    }
    if (materials.PaletteMaterial003) {
      materials.PaletteMaterial003.color.set(palette["--color-accent"]);
    }
    const mat004 = materials.PaletteMaterial004;
    if (mat004) {
      mat004.color.set(palette["--color-text"]);
      mat004.emissive.set(palette["--color-text"]);
      // eslint-disable-next-line react-hooks/immutability
      mat004.emissiveIntensity = 0.4;
    }
  }, [materials, palette]);

  const projectedLocation = useProjectedLocation();

  const transformedLocation = useMemo(() => {
    if (!projectedLocation) return null;
    if (!coordinateScales) return null;
    if (projectedLocation.index === 0) return null;

    return transformCoordinates(
      [projectedLocation.coords],
      coordinateScales,
      projectedLocation.index,
    )[0];
  }, [projectedLocation, coordinateScales]);

  const [springs, api] = useSpring(() => ({
    position: transformedLocation
      ? [
          transformedLocation[0],
          transformedLocation[1] + 0.2,
          transformedLocation[2],
        ]
      : [0, 0, 0],
    config: { tension: 170, friction: 26 },
  }));

  useEffect(() => {
    if (!transformedLocation) return;

    const x = transformedLocation[0];
    const y = transformedLocation[1];
    const z = transformedLocation[2];

    // Ensure all values are valid numbers before animating
    if (!Number.isFinite(x) || !Number.isFinite(y) || !Number.isFinite(z)) {
      return;
    }

    api.start({
      position: [x, y + 0.2, z],
    });
  }, [transformedLocation, api]);

  const { bounceY } = useSpring({
    from: { bounceY: -0.05 },
    to: { bounceY: 0.05 },
    loop: { reverse: true },
    config: { tension: 60, friction: 10 },
  });

  return (
    <a.group ref={group} {...props} dispose={null} position={springs.position}>
      <a.group position-y={bounceY}>
        <group name="Sketchfab_Scene">
          <primitive object={nodes.GLTF_created_0_rootJoint} />
          <skinnedMesh
            name="Object_7"
            geometry={nodes.Object_7.geometry}
            material={materials.PaletteMaterial001}
            skeleton={nodes.Object_7.skeleton}
            scale={1.21}
          />
          <skinnedMesh
            name="Object_8"
            geometry={nodes.Object_8.geometry}
            material={materials.PaletteMaterial001}
            skeleton={nodes.Object_8.skeleton}
            scale={1.21}
          />
          <skinnedMesh
            name="Object_9"
            geometry={nodes.Object_9.geometry}
            material={materials.PaletteMaterial002}
            skeleton={nodes.Object_9.skeleton}
            scale={1.21}
          />
          <skinnedMesh
            name="Object_10"
            geometry={nodes.Object_10.geometry}
            material={materials.PaletteMaterial003}
            skeleton={nodes.Object_10.skeleton}
            scale={1.21}
          />
          <skinnedMesh
            name="Object_11"
            geometry={nodes.Object_11.geometry}
            material={materials.PaletteMaterial004}
            skeleton={nodes.Object_11.skeleton}
            scale={1.21}
          />
        </group>
      </a.group>
    </a.group>
  );
}

useGLTF.preload("/scene-transformed.glb");
