// Message types for worker communication
// Used in both worker.js and gpxWorker.js

export const MESSAGE_TYPES = {
  REQUEST: {
    PROCESS_GPX_FILE: "PROCESS_GPX_FILE",
    PROCESS_GPS_DATA: "PROCESS_GPS_DATA",
    PROCESS_SECTIONS: "PROCESS_SECTIONS",
    CALCULATE_ROUTE_STATS: "CALCULATE_ROUTE_STATS",
    FIND_POINTS_AT_DISTANCES: "FIND_POINTS_AT_DISTANCES",
    GET_ROUTE_SECTION: "GET_ROUTE_SECTION",
    FIND_CLOSEST_LOCATION: "FIND_CLOSEST_LOCATION",
  },
  RESPONSE: {
    GPX_FILE_PROCESSED: "GPX_FILE_PROCESSED",
    GPS_DATA_PROCESSED: "GPS_DATA_PROCESSED",
    SECTIONS_PROCESSED: "SECTIONS_PROCESSED",
    ROUTE_STATS_CALCULATED: "ROUTE_STATS_CALCULATED",
    POINTS_FOUND: "POINTS_FOUND",
    ROUTE_SECTION_READY: "ROUTE_SECTION_READY",
    CLOSEST_POINT_FOUND: "CLOSEST_POINT_FOUND",
    PROGRESS: "PROGRESS",
    ERROR: "ERROR",
  },
};

export const SUCCESS_RESPONSE_TYPES = new Set([
  MESSAGE_TYPES.RESPONSE.GPX_FILE_PROCESSED,
  MESSAGE_TYPES.RESPONSE.GPS_DATA_PROCESSED,
  MESSAGE_TYPES.RESPONSE.SECTIONS_PROCESSED,
  MESSAGE_TYPES.RESPONSE.ROUTE_STATS_CALCULATED,
  MESSAGE_TYPES.RESPONSE.POINTS_FOUND,
  MESSAGE_TYPES.RESPONSE.ROUTE_SECTION_READY,
  MESSAGE_TYPES.RESPONSE.CLOSEST_POINT_FOUND,
]);
